title: registry
description: An open-source, extendable EToH Multi-Tower Kit.
url: https://stamper-pkg.github.io

plugins:
  - jekyll-remote-theme

remote_theme: just-the-docs/just-the-docs
color_scheme: stamper_dark

enable_copy_code_button: true

callouts:
  warning:
    title: Warning
    color: red

aux_links:
  GitHub:
    - https://github.com/stamper-luau/stamper